package mainPackage;


import java.awt.Color;

import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author soria
 */
public class deleteArray extends javax.swing.JFrame {

    /**
     * Creates new form deleteArray
     */
    public deleteArray() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        insBut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(359, 470));
        setResizable(false);
        getContentPane().setLayout(null);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(6, 6, 64, 23);

        jTextField1.setColumns(5);
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(130, 220, 69, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Enter a value to delete");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 200, 140, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("ARRAY CRUDS");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 130, 170, 32);

        insBut.setBackground(new java.awt.Color(255, 0, 0));
        insBut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        insBut.setForeground(new java.awt.Color(255, 255, 255));
        insBut.setText("Delete");
        insBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insButActionPerformed(evt);
            }
        });
        getContentPane().add(insBut);
        insBut.setBounds(120, 260, 90, 27);

        Color bgColor = new Color(241, 250, 218);

        getContentPane().setBackground(bgColor);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        mainFrame backToMn = new mainFrame();
        backToMn.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void insButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insButActionPerformed
        // TODO add your handling code here:
        deleteMethod();
    }//GEN-LAST:event_insButActionPerformed
    
    private int deleteMethod() {
        if (createArray.numesLen == 0) {
            JOptionPane.showMessageDialog(this, "Array is not initialized.");
            return createArray.numesLen;
        }
        try {
//            for (int i=0;i<createArray.numesLen;i++){
//                System.out.println(numbers[i]);
//            }
            // Arrays.sort(numbers);
            int valFind = Integer.parseInt(jTextField1.getText());
            int j = find(valFind);
            if (j == createArray.numesLen) { // can’t find it
                JOptionPane.showMessageDialog(this, "Value '" + valFind + "' not found.");
                // bool = false;
            } else {
                for (int k = j; k < createArray.numbers.length - 1; k++){ // move bigger ones down
                    createArray.numbers[k] = createArray.numbers[k + 1];
                }
                createArray.numesLen--; // decrement size
                createArray.numbers[createArray.numbers.length - 1] = 0; //set the deleted value to zero to not duplicate the values when deleting
                JOptionPane.showMessageDialog(this, "Value '" + valFind + "' deleted");
                // bool = true;
                
                insertArray.newNums = new int[createArray.numesLen]; //to set the new length of the array
                for (int i=0;i<createArray.numbers.length-1 ;i++){    
                    insertArray.newNums[i] = createArray.numbers[i];
                }
                createArray.numbers = insertArray.newNums;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Enter a number!");
        }
        System.out.println(createArray.numesLen);
        return createArray.numesLen;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(deleteArray.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(deleteArray.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(deleteArray.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(deleteArray.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new deleteArray().setVisible(true);
            }
        });
    }
    
    public static int find(int searchKey) {
        for (int i = 0; i < createArray.numesLen; i++) {
            if (createArray.numbers[i] == searchKey) {
                return i; // found it
            }
        }
        return createArray.numesLen; // can't find it
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton insBut;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
